---
ENV:
  ip_address: '127.0.0.1'
  port: '8080'
  web_version: '1'

# This section is related to ui testing with selenium
RUN:
  browser_type: "chrome"
  chrome_type: "google-chrome"
  headless: True
  screenshot: True
  ignore_ssl: True
